SELECT
s0.COUPON_ID
,s0.PAYMENT
,s1.hry_id
,s0.PRODUCT_ID
,s2.YEAR_PROFIT
,s2.DAY_BORROW_DURATION
,sum(S1.SUBSIDY_VALUE) value
FROM BIDATA.S_PROMO_COUPON_CONSUMPTION S0
LEFT JOIN BIDATA.S_PROMO_ORDER_SUBSIDY_PLAN S1
on S0.TRANSACTION_ID=S1.ORDER_ID
left join DIM_PROD_P2P_LIST s2
on S0.PRODUCT_ID=s2.BID
LEFT JOIN BIDATA.DW_COUPON_GRANT S3
ON S0.COUPON_ID=S3.cou
where s0.COUPON_KIND=2
group BY s0.COUPON_ID,s0.PAYMENT,s1.hry_id,s0.PRODUCT_ID,s2.YEAR_PROFIT,s2.DAY_BORROW_DURATION
;

SELECT
to_char(s1.ACTIVATE_TIME,'yyyymmdd') the_date
,('0'||100*S0.SUBSIDY_RATE||'%') add_percent
,count(*) grant_count
,count(distinct S1.OWNER_HRY_ID) grant_user_count
,count(USAGE_TIME) user_count
FROM BIDATA.S_PROMO_COUPON_CATEGORY S0
LEFT JOIN BIDATA.DW_COUPON_GRANT S1
ON S0.ID=S1.CATEGORY_ID
WHERE S0.COUPON_KIND=2
AND  s1.ACTIVATE_TIME>to_date('20170511','yyyymmdd')
group by ('0'||100*S0.SUBSIDY_RATE||'%'),to_char(s1.ACTIVATE_TIME,'yyyymmdd')
order by ('0'||100*S0.SUBSIDY_RATE||'%'),to_char(s1.ACTIVATE_TIME,'yyyymmdd')
;