SELECT
S1.THE_MONTH
,S0.DIS_CHANNEL_TYPE
,S0.ACTIVITY_TYPE_NAME 活动类型
,COUNT(*) 笔数
,sum(S0.REWARDS_AMT) amt
FROM BIDATA.DW_LCJ_GRANT S0
LEFT JOIN BIDIM.DIM_DATE S1
ON S0.DATE_KEY=S1.DATE_KEY
group by S1.THE_MONTH,S0.DIS_CHANNEL_TYPE,S0.ACTIVITY_TYPE_NAME
;

select * from bi_sync_table

SELECT
S1.THE_MONTH
,S0.DIS_CHANNEL_TYPE
,S0.ACTIVITY_TYPE_NAME 活动类型
,COUNT(*) 笔数
,sum(S0.REWARDS_AMT) amt
FROM BIDATA.DW_COUPON_GRANT S0
LEFT JOIN BIDIM.DIM_DATE S1
ON S0.DATE_KEY=S1.DATE_KEY
group by S1.THE_MONTH,S0.DIS_CHANNEL_TYPE,S0.ACTIVITY_TYPE_NAME
;


SELECT
S1.THE_MONTH
,S0.DIS_CHANNEL_TYPE
,S0.ACTIVITY_TYPE_NAME 活动类型
,S0.ACTIVITY_NAME 活动名称
,COUNT(*) 笔数
,sum(S0.COUPON_VALUE) 金额
FROM BIDATA.DW_COUPON_GRANT S0
LEFT JOIN BIDIM.DIM_DATE S1
ON S0.DATE_KEY=S1.DATE_KEY
group by S1.THE_MONTH,S0.DIS_CHANNEL_TYPE,S0.ACTIVITY_NAME,S0.ACTIVITY_TYPE_NAME
;