CREATE TABLE K_CHANNEL_ODS_ODS.FUND_CHANNEL_INC (
	FUND_CHANNEL_CODE VARCHAR2(32 BYTE) PRIMARY KEY
	,NAME VARCHAR2(64 BYTE)
	,DESCRIPTION VARCHAR2(256 BYTE) 
	,INST_CODE VARCHAR2(16 BYTE)
	,BIZ_TYPE CHAR(1 BYTE)
	,PAY_MODE VARCHAR2(16 BYTE)
	,SIGNED_CROP CHAR(1 BYTE)
	,STATUS VARCHAR2(16 BYTE)
	,VALID_FROM TIMESTAMP(6)
	,VALID_TO TIMESTAMP(6)
	,MAX_AMOUNT NUMBER(15,2)
	,MIN_AMOUNT NUMBER(15,2)
	,EXPECT_ARRIVE_TIME VARCHAR2(16 BYTE)
	,GMT_CREATE TIMESTAMP(6)
	,GMT_MODIFIED TIMESTAMP(6)
	,MEMO VARCHAR2(128 BYTE) 
	,CHANNEL_MODE VARCHAR2(16 BYTE) 
	,PRIORITY NUMBER(2, 0) 
);

COMMENT ON TABLE K_CHANNEL_ODS.FUND_CHANNEL_INC IS '资金渠道';

COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.FUND_CHANNEL_CODE IS '渠道编码';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.NAME IS '渠道名称';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.DESCRIPTION IS '渠道描述';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.INST_CODE IS '机构代码';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.BIZ_TYPE IS '业务类型：I（入款），O（出款）';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.PAY_MODE IS '支付方式，如：网银，卡通，线下，手机充值卡，手机话费，微汇卡，积分。。。';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.SIGNED_CROP IS '签约公司：Y（益充），S（微汇）';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.STATUS IS '是否可用：VALID（可用），INVALID（不可用）';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.EXPECT_ARRIVE_TIME IS 'T+15M表示15分钟到帐，T+1D表示一天到帐，H小时';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.GMT_MODIFIED IS '最后修改时间';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.MEMO IS '备注';
COMMENT ON COLUMN K_CHANNEL_ODS.FUND_CHANNEL_INC.PRIORITY IS '此优先级在过滤，优选之后使用';
