WITH TMP_WORK_ORDER AS (
SELECT
TO_CHAR(S0.create_time,'YYYYMMDD') AUDIT_DATE
,S0.MEMBER_ID KJTID
,DECODE(S1.MEMBER_TYPE,1,'个人',2,'企业',3,'特约商户') MEMBER_TYPE_NAME
,S0.MEMBER_ACCOUNT
,S0.ORDER_TYPE ORDER_TYPE_CODE
,DECODE(S0.ORDER_TYPE,100,'三证齐全状态审核[企业会员]',101,'个人会员影印件审核',102,'企业会员影印件审核',103,'特约商户会员影印件审核') ORDER_TYPE_NAME
,DECODE(S0.ORDER_STATUS,1,'处理中',2,'处理完成') ORDER_STATUS_NAME
,DECODE(S0.AUDIT_STATUS,1,'未审核',2,'通过',3,'驳回') AUDIT_STATUS_NAME
,S0.CREATE_TIME
,S0.CREATE_OPERATOR
,S0.AUDIT_OPERATOR
,S0.AUDIT_TIME
FROM basis.tb_work_order@KJTDB S0
LEFT JOIN MEMBER.TM_MEMBER@KJTDB S1
ON S0.MEMBER_ID=S1.MEMBER_ID
WHERE S0.AUDIT_STATUS='2'
AND S1.MEMBER_TYPE>1
AND TO_CHAR(S0.audit_time,'YYYYMM')='201704'
--AND TO_CHAR(S0.create_time,'YYYYMM')='201704'
)

SELECT
MEMBER_TYPE_NAME
,COUNT(DISTINCT KJTID) MEMBER_COUNT
FROM TMP_WORK_ORDER
GROUP BY MEMBER_TYPE_NAME
;