WITH TMP_COUPON_GRANT AS (
SELECT 
S1.THE_MONTH
,COUNT(S0.COUPON_ID) 发放券张数
,SUM(S0.COUPON_VALUE) 发放券总额
FROM BIDATA.DW_COUPON_GRANT S0
LEFT JOIN BIDIM.DIM_DATE S1
ON S0.DATE_KEY=S1.DATE_KEY
GROUP BY S1.THE_MONTH
ORDER BY S1.THE_MONTH DESC),
TMP_COUPON_OVERDUE AS (
SELECT
S1.THE_MONTH
,COUNT(*) 过期券张数
,SUM(S0.COUPON_VALUE) 过期券总额
FROM BIDATA.DW_COUPON_GRANT S0
LEFT JOIN BIDIM.DIM_DATE S1
ON TO_CHAR(S0.EFFECTIVE_TIME,'YYYYMMDD')=S1.DATE_KEY
WHERE S0.COUPON_STATUS_ID=4
GROUP BY S1.THE_MONTH 
ORDER BY S1.THE_MONTH DESC
),
TMP_COUPON_USE AS (
select
S1.the_month
,count(S0.INVEST_COUPON_AMOUNT) 使用券张数
,sum(S0.INVEST_COUPON_AMOUNT) 使用券金额
from BIDATA.DM_ORDER_P2P_OK S0
LEFT JOIN BIDIM.DIM_DATE S1
ON S0.DATE_KEY=S1.DATE_KEY
where S0.INVEST_COUPON_AMOUNT>0
group by S1.the_month)


SELECT
S0.THE_MONTH 月份
,S1.发放券张数
,S1.发放券总额
,S2.过期券张数
,S2.过期券总额
,S3.使用券张数
,S3.使用券金额
,sum((nvl(S1.发放券张数,0)-nvl(S2.过期券张数,0)-nvl(S3.使用券张数,0))) over (order by S0.THE_MONTH) 存量张数
,sum((nvl(S1.发放券总额,0)-nvl(S2.过期券总额,0)-nvl(S3.使用券金额,0))) over (order by S0.THE_MONTH) 存量金额
FROM (
SELECT DISTINCT S0.THE_MONTH FROM BIDIM.DIM_DATE S0 ORDER BY S0.THE_MONTH
) S0
LEFT JOIN TMP_COUPON_GRANT S1
ON S0.THE_MONTH=S1.THE_MONTH
LEFT JOIN TMP_COUPON_OVERDUE S2
ON S0.THE_MONTH=S2.THE_MONTH
LEFT JOIN TMP_COUPON_USE S3
ON S0.THE_MONTH=S3.THE_MONTH
where S0.THE_MONTH<=to_char(sysdate,'yyyymm') 
AND S0.THE_MONTH>201601
ORDER BY S0.THE_MONTH 
;
