package com.banggo.scheduler.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.SqlMapClientTemplate;

import com.banggo.scheduler.dao.daointerface.ScheAlarmDAO;
import com.banggo.scheduler.dao.dataobject.ScheAlarm;
import com.banggo.scheduler.dao.dataobject.ScheAlarmMore;

public class ScheAlarmDAOImpl implements ScheAlarmDAO {
	private SqlMapClientTemplate sqlMapClient;

	public void setSqlMapClient(SqlMapClientTemplate sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_ALARM
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void insert(ScheAlarm record) throws DataAccessException {
        sqlMapClient.insert("SCHE_ALARM.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_ALARM
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int updateByPrimaryKey(ScheAlarm record) throws DataAccessException {
        int rows = sqlMapClient.update("SCHE_ALARM.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_ALARM
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int updateByPrimaryKeySelective(ScheAlarm record) throws DataAccessException {
        int rows = sqlMapClient.update("SCHE_ALARM.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_ALARM
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public ScheAlarm selectByPrimaryKey(Integer id) throws DataAccessException {
        ScheAlarm key = new ScheAlarm();
        key.setId(id);
        ScheAlarm record = (ScheAlarm) sqlMapClient.queryForObject("SCHE_ALARM.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_ALARM
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) throws DataAccessException {
        ScheAlarm key = new ScheAlarm();
        key.setId(id);
        int rows = sqlMapClient.delete("SCHE_ALARM.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<ScheAlarmMore> select(Map params) {
		return sqlMapClient.queryForList("SCHE_ALARM.selectList", params);
	}

	@Override
	public int count(Map params) {
		Integer count = (Integer) sqlMapClient.queryForObject("SCHE_ALARM.count", params);
		return  count != null? count.intValue() : 0;
	}

	
}