 

CREATE TABLE K_TRADE.DWD_TSS_PAY_METHOD_D  
(
  PAY_METHOD_ID NUMBER(11, 0) NOT NULL PRIMARY KEY
, PAYMENT_VOUCHER_NO VARCHAR2(32 BYTE) NOT NULL 
, AMOUNT NUMBER(15, 2) NOT NULL 
, PAY_MODE VARCHAR2(32 BYTE) NOT NULL 
, PAY_CHANNEL VARCHAR2(32 BYTE) NOT NULL 
, PROPS VARCHAR2(1000 BYTE) 
, EXTENSION VARCHAR2(4000 BYTE) 
, INST_PAY_NO VARCHAR2(32 BYTE) 
, RESULT_EXT VARCHAR2(1000 BYTE) 
, GMT_PAY TIMESTAMP(6) 
, UNIT_RESULT_CODE VARCHAR2(32 BYTE) 
, UNIT_RESULT_MSG VARCHAR2(256 BYTE) 
, GMT_CREATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) 
, DW_CREATE_TIME DATE DEFAULT sysdate
, DW_MODIFIED_TIME DATE
)  
PARTITION BY RANGE ("GMT_CREATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) (PARTITION "P_MONTH_1"  VALUES LESS THAN (TO_DATE('20150101','YYYYMMDD')));


COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.PAY_METHOD_ID IS '支付渠道ID';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.PAYMENT_VOUCHER_NO IS '支付凭证号';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.AMOUNT IS '金额';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.PAY_MODE IS '支付模式';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.PAY_CHANNEL IS '支付渠道';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.PROPS IS '渠道属性';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.EXTENSION IS '扩展参数';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.INST_PAY_NO IS '提交机构订单号';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.RESULT_EXT IS '渠道结果扩展参数';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.GMT_PAY IS '支付完成时间';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.UNIT_RESULT_CODE IS '统一返回码';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.UNIT_RESULT_MSG IS '统一返回信息';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.GMT_MODIFIED IS '修改时间';
COMMENT ON TABLE K_TRADE.DWD_TSS_PAY_METHOD_D IS '支付方式';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.DW_CREATE_TIME IS 'DW 创建时间';
COMMENT ON COLUMN K_TRADE.DWD_TSS_PAY_METHOD_D.DW_MODIFIED_TIME IS 'DW 修改时间';