INSERT INTO K_TRADE.DWD_TSS_TRADE_FEE_D
SELECT 
  t.*
  ,sysdate
  ,sysdate
FROM tss.T_TRADE_FEE@kjtdb t
WHERE GMT_CREATE >= to_date('20170101','YYYYMMDD') --and GMT_CREATE < to_date('20170201','YYYYMMDD');

