DROP   TABLE K_TRADE.DWS_TRADE_BY_MEMBER_D ;

CREATE TABLE K_TRADE.DWS_TRADE_BY_MEMBER_D
AS
SELECT 
   TO_CHAR(TRADE_GMT_CREATE,'YYYYMMDD') DATE_ID
  ,TRADE_SOURCE
  ,PRODUCT_CODE
  ,BIZ_PRODUCT_CODE
  ,BIZ_PRODUCT_CODE_DESC
  ,TRADE_TYPE
  ,TRADE_TYPE_DESC
  ,PAY_MODE
  ,PAY_MODE_DESC
  ,PAYEE_MEMBER_ID
  ,PAYEE_MEMBER_TYPE
  ,PAYER_MEMBER_ID
  ,PAYER_MEMBER_TYPE
  ,Accounting_TYPE
  ,Accounting_OWNER_ID
  ,FUND_CHANNEL_CODE
  ,CHANNEL_ORDER_TYPE
  ,REAL_PAY_MODE
  ,REAL_PAY_MODE_DESC
  ,CASE WHEN FUND_CHANNEL_CODE is NOT NULL THEN 'BANK_ACCOUNT'
    ELSE 'KJT_ACCOUNT'
   END PAY_ACCOUNT_TYPE
  ,COUNT(1) CNT
  ,SUM(AMOUNT) AMOUNT
FROM K_TRADE.DWD_TRADE_DETAIL_D  --PARTITION(P201705)
WHERE   TRADE_PAYMENT_STATUS in ('S')
AND (
   (TRADE_SOURCE ='TSS'
   AND (
           TRADE_TYPE in ('01') 
        or (TRADE_TYPE in ('14')  and TRADE_PAYMENT_TYPE in ( '04'))
        or (TRADE_TYPE not in ('01','14') and TRADE_PAYMENT_TYPE in ( '01','04'))
       ))
    OR TRADE_SOURCE IN ('FOS','DEPOSIT')
   ) 
GROUP BY   
   TO_CHAR(TRADE_GMT_CREATE,'YYYYMMDD')  
  ,TRADE_SOURCE
  ,PRODUCT_CODE
  ,BIZ_PRODUCT_CODE
  ,BIZ_PRODUCT_CODE_DESC
  ,TRADE_TYPE
  ,TRADE_TYPE_DESC
  ,PAY_MODE
  ,PAY_MODE_DESC
  ,PAYEE_MEMBER_ID
  ,PAYEE_MEMBER_TYPE
  ,PAYER_MEMBER_ID
  ,PAYER_MEMBER_TYPE
  ,Accounting_TYPE
  ,Accounting_OWNER_ID
  ,FUND_CHANNEL_CODE
  ,CHANNEL_ORDER_TYPE
  ,REAL_PAY_MODE
  ,REAL_PAY_MODE_DESC ;
  
  
  
  SELECT  BIZ_PRODUCT_CODE
    ,BIZ_PRODUCT_CODE_DESC
    ,TRADE_TYPE_DESC
    --,ACCOUNTING_TYPE
    ,COALESCE (REAL_PAY_MODE_DESC,PAY_MODE_DESC) PAY_MODE_DESC
    ,SUM(CNT) CNT
    ,SUM(AMOUNT) AMOUNT
  FROM K_TRADE.DWS_TRADE_BY_MEMBER_D
  WHERE 1=1
   --AND ACCOUNTING_TYPE in ('绩效收款','绩效付款')
   AND BIZ_PRODUCT_CODE in ('10104','10210','10211','10220','10221',
   '10223','10226','10230','10231',
   '10240','10241','10243','10245',
   '10310','10311','10312','20204','20401','20402','20403','20601','90110')
   AND SUBSTR(DATE_ID,1,6) = '201705'
   --AND TRADE_SOURCE ='TSS'
  GROUP BY BIZ_PRODUCT_CODE
    ,BIZ_PRODUCT_CODE_DESC
    ,TRADE_TYPE_DESC
    --,ACCOUNTING_TYPE
    ,COALESCE (REAL_PAY_MODE_DESC,PAY_MODE_DESC)
  ORDER BY BIZ_PRODUCT_CODE;
  
  
  
WITH D AS (
 SELECT  
     TRADE_VOUCHER_NO
     ,PAYMENT_VOUCHER_NO
     ,PAYMENT_SEQ_NO
     ,BIZ_PRODUCT_CODE
    ,BIZ_PRODUCT_CODE_DESC
    ,TRADE_TYPE
    ,TRADE_TYPE_DESC
    --,ACCOUNTING_TYPE
    ,PAY_MODE_DESC
    ,REAL_PAY_MODE_DESC 
    ,TRADE_GMT_CREATE
    ,TRADE_PAYMENT_TYPE
    ,SUBSTR(TRADE_GMT_CREATE,1,6)
    
    
    
  FROM K_TRADE.DWD_TRADE_DETAIL_D  
  WHERE BIZ_PRODUCT_CODE = '20401'
   AND to_char(TRADE_GMT_CREATE,'YYYYMM') = '201705'
   AND REAL_PAY_MODE_DESC IS NOT NULL)
SELECT *   FROM D WHERE PAY_MODE_DESC = '余额'

--'余额支付' 支付方式,'转账出款' 支付类型,'普通转账交易' 交易类型,

支付方式,'出款' 支付类型,'出款' 交易类型,

WITH T AS (
SELECT 
  SUBSTR(DATE_ID,1,6) MONTH_ID
 ,BIZ_PRODUCT_CODE
 ,BIZ_PRODUCT_CODE_DESC
 ,COALESCE(REAL_PAY_MODE_DESC,PAY_MODE_DESC) PAY_MODE_DESC
 ,CASE 
  WHEN TRADE_SOURCE = 'FOS' THEN '出款'
  WHEN TRADE_SOURCE = 'DEPOSIT' THEN '充值'
  WHEN TRADE_TYPE = '01' THEN '转账出款'
  WHEN CHANNEL_ORDER_TYPE IS NOT NULL  THEN DECODE(CHANNEL_ORDER_TYPE,'I','入款','B','退款','O','代发退款',CHANNEL_ORDER_TYPE)
  ELSE '收单入款' 
 END PAY_TYPE
 ,CASE 
  WHEN TRADE_SOURCE = 'FOS' THEN '出款'
  WHEN TRADE_SOURCE = 'DEPOSIT' THEN '充值'
  WHEN TRADE_TYPE = '01' THEN '普通转账交易'
  ELSE TRADE_TYPE_DESC
 END TRADE_TYPE
 ,CNT
 ,AMOUNT
FROM K_TRADE.DWS_TRADE_BY_MEMBER_D
WHERE TRADE_SOURCE in ( 'FOS')
 --AND BIZ_PRODUCT_CODE = '20401'
 AND SUBSTR(DATE_ID,1,6) >= '201705' AND SUBSTR(DATE_ID,1,6) <= '201705'
 )
--SELECT SUM(AMOUNT) FROM T 
 
SELECT 
   MONTH_ID
  ,BIZ_PRODUCT_CODE
  ,BIZ_PRODUCT_CODE_DESC
  ,PAY_MODE_DESC
  ,PAY_TYPE
  ,TRADE_TYPE
  ,SUM(CNT) CNT 
  ,SUM(AMOUNT) AMOUNT
 FROM T
GROUP BY 
   MONTH_ID
  ,BIZ_PRODUCT_CODE
  ,BIZ_PRODUCT_CODE_DESC
  ,PAY_MODE_DESC
  ,PAY_TYPE
  ,TRADE_TYPE
ORDER BY 
   MONTH_ID
  ,BIZ_PRODUCT_CODE
  ,AMOUNT
 
 
SELECT    
  TRADE_STATUS
  ,SUM(AMOUNT) 
FROM K_TRADE.DWD_TRADE_DETAIL_D
WHERE TRADE_SOURCE = 'TSS'
 AND TRADE_PAYMENT_STATUS = 'S'
 GROUP BY TRADE_STATUS