CREATE TABLE K_TRADE_ODS.PAYMENT_PARTY_INC
(
  PAYMENT_PARTY_ID NUMBER(15, 0) NOT NULL PRIMARY KEY
, PAYMENT_SEQ_NO VARCHAR2(32 BYTE) NOT NULL 
, PARTY_ID_TYPE VARCHAR2(10 BYTE) NOT NULL 
, PARTY_ID VARCHAR2(64 BYTE) NOT NULL 
, ACCOUNT_NO VARCHAR2(32 BYTE) 
, FUND_PROP_TYPE CHAR(2 BYTE) 
, ROLE_CODE VARCHAR2(50 BYTE) NOT NULL 
, AMOUNT NUMBER(15, 2) NOT NULL 
, FREEZE_AMOUNT NUMBER(15, 2) NOT NULL 
, UNFREEZE_AMOUNT NUMBER(15, 2) NOT NULL 
, CHARGE_FEE NUMBER(15, 2) NOT NULL 
, RETURN_FEE NUMBER(15, 2) NOT NULL 
, EXTENSION VARCHAR2(4000 BYTE) 
, GMT_CREATE TIMESTAMP(6) NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) NOT NULL 
);



TRUNCATE TABLE K_TRADE_ODS.PAYMENT_PARTY_INC;
INSERT /*+ append nologging */ INTO K_TRADE_ODS.PAYMENT_PARTY_INC
SELECT *
FROM payment.tb_party_payment@kjtdb  
WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;


DELETE FROM  K_TRADE.DWD_PAYMENT_PARTY_D WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;
 
INSERT /*+   nologging */ INTO K_TRADE.DWD_PAYMENT_PARTY_D
SELECT 
	  t.*
	  ,sysdate DW_CREATE_TIME
	  ,sysdate DW_MODIFIED_TIME
FROM K_TRADE_ODS.PAYMENT_PARTY_INC t;


 