CREATE TABLE K_TRADE_ODS.PAYMENT_ORDER_INC
(
  PAYMENT_SEQ_NO VARCHAR2(32 BYTE)  
, BIZ_PAYMENT_SEQ_NO VARCHAR2(32 BYTE) NOT NULL 
, RELATE_PAYMENT_SEQ_NO VARCHAR2(32 BYTE) 
, PAYMENT_TYPE VARCHAR2(10 BYTE) NOT NULL 
, PRODUCT_CODE VARCHAR2(32 BYTE) NOT NULL 
, PAYMENT_CODE VARCHAR2(16 BYTE) NOT NULL 
, PRODUCT_ORDER_NO VARCHAR2(64 BYTE) NOT NULL 
, PAYMENT_ORDER_NO VARCHAR2(64 BYTE) NOT NULL 
, GMT_PAYMENT TIMESTAMP(6) NOT NULL 
, GMT_CREATE TIMESTAMP(6) NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) NOT NULL 
, MEMO VARCHAR2(256 BYTE) 
, PAY_MODE VARCHAR2(32 BYTE) 
, PAY_CHANNEL VARCHAR2(16 BYTE) 
, PS_CODE VARCHAR2(16 BYTE) 
, AUTO_SETTLE CHAR(1 BYTE) 

)



TRUNCATE TABLE K_TRADE_ODS.PAYMENT_ORDER_INC;
INSERT /*+ append nologging */ INTO K_TRADE_ODS.PAYMENT_ORDER_INC
SELECT *
FROM payment.tb_payment_order@kjtdb  
WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;


DELETE FROM  K_TRADE.DWD_PAYMENT_ORDER_D WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;
 
INSERT /*+   nologging */ INTO K_TRADE.DWD_PAYMENT_ORDER_D
SELECT 
	  t.*
	  ,sysdate DW_CREATE_TIME
	  ,sysdate DW_MODIFIED_TIME
FROM K_TRADE_ODS.PAYMENT_ORDER_INC t;


 
