CREATE TABLE K_TRADE_ODS.FUNDOUT_ORDER_INC
(
  FUNDOUT_ORDER_NO VARCHAR2(32 BYTE) NOT NULL 
, PRODUCT_CODE VARCHAR2(32 BYTE) NOT NULL 
, MEMBER_ID VARCHAR2(32 BYTE) NOT NULL 
, ACCOUNT_NO VARCHAR2(32 BYTE) NOT NULL 
, AMOUNT NUMBER(18, 2) NOT NULL 
, FEE NUMBER(18, 2) NOT NULL 
, CARD_ID VARCHAR2(32 BYTE) 
, CARD_NO VARCHAR2(32 BYTE) 
, CARD_TYPE CHAR(2 BYTE) 
, NAME VARCHAR2(256 BYTE) 
, BANK_CODE VARCHAR2(32 BYTE) 
, BANK_NAME VARCHAR2(64 BYTE) 
, BRANCH_NAME VARCHAR2(256 BYTE) 
, BANK_LINE_NO CHAR(12 BYTE) 
, PROV VARCHAR2(64 BYTE) 
, CITY VARCHAR2(64 BYTE) 
, COMPANY_PERSONAL CHAR(1 BYTE) 
, PURPOSE VARCHAR2(256 BYTE) 
, FUNDOUT_GRADE CHAR(1 BYTE) 
, STATUS VARCHAR2(16 BYTE) 
, NOTIFY_STATUS CHAR(1 BYTE) 
, ORDER_TIME DATE 
, RESULT_TIME DATE 
, EXTENSION VARCHAR2(2000 BYTE) 
, GMT_CREATE DATE 
, GMT_MODIFY DATE 
, ACCOUNT_TYPE VARCHAR2(32 BYTE) 
, RESULT_DESC VARCHAR2(256 BYTE) 
, BATCH_ORDER_NO VARCHAR2(32 BYTE) 
, SUBMITTOR_ID VARCHAR2(32 BYTE) 
, REFUND_ORDER_NO VARCHAR2(32 BYTE) 
, REFUND_TIME DATE 
, OUT_ORDER_NO VARCHAR2(64 BYTE) 
, SOURCE_BATCH_NO VARCHAR2(32 BYTE) 
) ；



TRUNCATE TABLE K_TRADE_ODS.FUNDOUT_ORDER_INC;
INSERT /*+ append nologging */ INTO K_TRADE_ODS.FUNDOUT_ORDER_INC
SELECT *
FROM fos.tt_fundout_order@kjtdb  
WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;


DELETE FROM  K_TRADE.DWD_FUNDOUT_ORDER_D WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;
 
INSERT /*+   nologging */ INTO K_TRADE.DWD_FUNDOUT_ORDER_D
SELECT 
	  t.*
	  ,sysdate DW_CREATE_TIME
	  ,sysdate DW_MODIFIED_TIME
FROM K_TRADE_ODS.FUNDOUT_ORDER_INC t;

