CREATE TABLE K_TRADE_ODS.FUNDOUT_PAYMENT_ORDER_INC
(
  PAYMENT_ORDER_NO VARCHAR2(32 BYTE)  
, FUNDOUT_ORDER_NO VARCHAR2(32 BYTE) 
, MEMBER_ID VARCHAR2(32 BYTE) 
, PRODUCT_CODE VARCHAR2(32 BYTE) 
, ACCOUNT_NO VARCHAR2(32 BYTE) 
, BANK_CODE VARCHAR2(32 BYTE) 
, CARD_NO VARCHAR2(32 BYTE) 
, AMOUNT NUMBER(18, 2) 
, FEE NUMBER(18, 2) 
, STATUS VARCHAR2(16 BYTE) 
, NOTIFY_STATUS CHAR(1 BYTE) 
, ORDER_TIME DATE 
, RESULT_TIME DATE 
, EXTENSION VARCHAR2(2000 BYTE) 
, GMT_CREATE DATE 
, GMT_MODIFY DATE 
, NAME VARCHAR2(256 BYTE) 
, COMPANY_PERSONAL CHAR(1 BYTE) 
, BATCH_ORDER_NO VARCHAR2(32 BYTE) 
, SUBMITTOR_ID VARCHAR2(32 BYTE) 
, REFUND_ORDER_NO VARCHAR2(32 BYTE) 
, REFUND_TIME DATE 
, SOURCE_BATCH_NO VARCHAR2(32 BYTE) 
) 


TRUNCATE TABLE K_TRADE_ODS.FUNDOUT_PAYMENT_ORDER_INC;
INSERT /*+ append nologging */ INTO K_TRADE_ODS.FUNDOUT_PAYMENT_ORDER_INC
SELECT *
FROM fos.tt_payment_order@kjtdb  
WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;


DELETE FROM  K_TRADE.DWD_FUNDOUT_PAYMENT_ORDER_D WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;
 
INSERT /*+   nologging */ INTO K_TRADE.DWD_FUNDOUT_PAYMENT_ORDER_D
SELECT 
	  t.*
	  ,sysdate DW_CREATE_TIME
	  ,sysdate DW_MODIFIED_TIME
FROM K_TRADE_ODS.FUNDOUT_PAYMENT_ORDER_INC t;


 