CREATE TABLE K_TRADE_ODS.TSS_PAY_METHOD_INC
(
  PAY_METHOD_ID NUMBER(11, 0) NOT NULL PRIMARY KEY
, PAYMENT_VOUCHER_NO VARCHAR2(32 BYTE) NOT NULL 
, AMOUNT NUMBER(15, 2) NOT NULL 
, PAY_MODE VARCHAR2(32 BYTE) NOT NULL 
, PAY_CHANNEL VARCHAR2(32 BYTE) NOT NULL 
, PROPS VARCHAR2(1000 BYTE) 
, EXTENSION VARCHAR2(4000 BYTE) 
, INST_PAY_NO VARCHAR2(32 BYTE) 
, RESULT_EXT VARCHAR2(1000 BYTE) 
, GMT_PAY TIMESTAMP(6) 
, UNIT_RESULT_CODE VARCHAR2(32 BYTE) 
, UNIT_RESULT_MSG VARCHAR2(256 BYTE) 
, GMT_CREATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) 
)  

 


TRUNCATE TABLE K_TRADE_ODS.TSS_PAY_METHOD_INC;
INSERT /*+ append nologging */ INTO K_TRADE_ODS.TSS_PAY_METHOD_INC
SELECT *
FROM tss.t_pay_method@kjtdb  
WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;


DELETE FROM  K_TRADE.DWD_TSS_PAY_METHOD_D WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;
 
INSERT /*+   nologging */ INTO K_TRADE.DWD_TSS_PAY_METHOD_D
SELECT 
	  t.*
	  ,sysdate DW_CREATE_TIME
	  ,sysdate DW_MODIFIED_TIME
FROM K_TRADE_ODS.TSS_PAY_METHOD_INC t;


  