
 
CREATE TABLE K_TRADE_ODS.DEPOSIT_PAYMENT_ORDER_INC 
(
  PAYMENT_VOUCHER_NO VARCHAR2(32 BYTE) NOT NULL  
, TRADE_VOUCHER_NO VARCHAR2(32 BYTE) 
, PRODUCT_CODE VARCHAR2(16 BYTE) NOT NULL 
, MEMBER_ID VARCHAR2(32 BYTE) NOT NULL 
, ACCOUNT_NO VARCHAR2(32 BYTE) 
, AMOUNT NUMBER(15, 2) NOT NULL 
, FEE NUMBER(15, 2) 
, PAY_MODE VARCHAR2(32 BYTE) 
, PAY_CHANNEL VARCHAR2(32 BYTE) 
, REMARK VARCHAR2(128 BYTE) 
, GMT_PAY_SUBMIT TIMESTAMP(6) 
, PAYMENT_STATUS VARCHAR2(16 BYTE) 
, EXT VARCHAR2(4000 BYTE) 
, BIZ_PAYMENT_SEQ_NO VARCHAR2(32 BYTE) 
, BIZ_PAYMENT_STATE VARCHAR2(16 BYTE) 
, BIZ_SUB_STATE VARCHAR2(16 BYTE) 
, INST_PAY_NO VARCHAR2(32 BYTE) 
, GMT_PAID TIMESTAMP(6) 
, ACCESS_CHANNEL VARCHAR2(16 BYTE) 
, GMT_CREATE TIMESTAMP(6) NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) 
, MERCHANT_NOTIFY_STATUS VARCHAR2(16 BYTE) 
, USER_NOTIFY_STATUS VARCHAR2(16 BYTE) 
);





TRUNCATE TABLE K_TRADE_ODS.DEPOSIT_PAYMENT_ORDER_INC;

INSERT /*+ append nologging */ INTO K_TRADE_ODS.DEPOSIT_PAYMENT_ORDER_INC
SELECT *
FROM DEPOSIT.T_PAYMENT_ORDER@kjtdb  
WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;


DELETE FROM  K_TRADE.DWD_DEPOSIT_PAYMENT_ORDER_D WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;
 
INSERT /*+   nologging */ INTO K_TRADE.DWD_DEPOSIT_PAYMENT_ORDER_D
SELECT 
	  t.*
	  ,sysdate DW_CREATE_TIME
	  ,sysdate DW_MODIFIED_TIME
FROM K_TRADE_ODS.DEPOSIT_PAYMENT_ORDER_INC t;