CREATE TABLE K_TRADE_ODS.TSS_TRADE_ORDER_INC
(
  TRADE_VOUCHER_NO VARCHAR2(32 BYTE) NOT NULL   
, TRADE_SRC_VOUCHER_NO VARCHAR2(64 BYTE) NOT NULL 
, ORIG_TRADE_VOUCHER_NO VARCHAR2(32 BYTE) 
, BIZ_NO VARCHAR2(64 BYTE) 
, BIZ_PRODUCT_CODE VARCHAR2(16 BYTE) NOT NULL 
, TRADE_AMOUNT NUMBER(15, 2) NOT NULL 
, TRADE_TYPE VARCHAR2(16 BYTE) NOT NULL 
, GMT_SUBMIT TIMESTAMP(6) NOT NULL 
, BUYER_ID VARCHAR2(32 BYTE) NOT NULL 
, BUYER_NAME VARCHAR2(128 BYTE) 
, SELLER_ID VARCHAR2(32 BYTE) NOT NULL 
, SELLER_NAME VARCHAR2(128 BYTE) 
, SELLER_ACCOUNT_NO VARCHAR2(32 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(32 BYTE) NOT NULL 
, PARTNER_NAME VARCHAR2(128 BYTE) 
, ACCESS_CHANNEL VARCHAR2(16 BYTE) NOT NULL 
, EXTENSION VARCHAR2(2000 BYTE) 
, PRE_STATUS VARCHAR2(16 BYTE) 
, STATUS VARCHAR2(16 BYTE) NOT NULL 
, TRADE_MEMO VARCHAR2(256 BYTE) 
, RESULT_MEMO VARCHAR2(256 BYTE) 
, ERROR_CODE VARCHAR2(16 BYTE) 
, ERROR_MSG VARCHAR2(256 BYTE) 
, GMT_CREATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) 
, IS_NOTIFIED CHAR(1 BYTE) 
, PROD_DESC VARCHAR2(1000 BYTE) 
, PROD_SHOW_URL VARCHAR2(256 BYTE) 
, RELATED_TRADE_VOUCHER_NO VARCHAR2(32 BYTE) 
, PROCESSOR_ID VARCHAR2(64 BYTE) 
, BATCH_NO VARCHAR2(32 BYTE) 
, SUBMIT_ID VARCHAR2(32 BYTE) 
, SOURCE_BATCH_NO VARCHAR2(32 BYTE) 

) 




TRUNCATE TABLE K_TRADE_ODS.TSS_TRADE_ORDER_INC;
INSERT /*+ append nologging */ INTO K_TRADE_ODS.TSS_TRADE_ORDER_INC
SELECT *
FROM tss.t_trade_order@kjtdb  
WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;

COMMIT;

DELETE FROM  K_TRADE.DWD_TSS_TRADE_ORDER_D WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;
 
INSERT /*+   nologging */ INTO K_TRADE.DWD_TSS_TRADE_ORDER_D
SELECT 
	  t.*
	  ,sysdate DW_CREATE_TIME
	  ,sysdate DW_MODIFIED_TIME
FROM K_TRADE_ODS.TSS_TRADE_ORDER_INC t;
 

