DROP TABLE K_TRADE_ODS.TSS_PAYMENT_ORDER_INC;
CREATE TABLE K_TRADE_ODS.TSS_PAYMENT_ORDER_INC
(
  PAYMENT_VOUCHER_NO VARCHAR2(32 BYTE) NOT NULL PRIMARY KEY
, PAYMENT_SOURCE_VOUCHER_NO VARCHAR2(64 BYTE) 
, ORIG_PAYMENT_VOUCHER_NO VARCHAR2(32 BYTE) 
, BIZ_PRODUCT_CODE VARCHAR2(16 BYTE) NOT NULL 
, IS_DUPLICATE CHAR(1 BYTE) 
, PAYMENT_TYPE VARCHAR2(16 BYTE) NOT NULL 
, PAYMENT_CODE VARCHAR2(16 BYTE) 
, AMOUNT NUMBER(15, 2) NOT NULL 
, STATUS VARCHAR2(16 BYTE) NOT NULL 
, GMT_SUBMIT TIMESTAMP(6) 
, ACCESS_CHANNEL VARCHAR2(16 BYTE) 
, ERROR_CODE VARCHAR2(16 BYTE) 
, ERROR_MSG VARCHAR2(256 BYTE) 
, GMT_CREATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) 
, PAYMENT_TAG VARCHAR2(16 BYTE) 
, TRADE_VOUCHER_NO VARCHAR2(32 BYTE) 
, PROCESSOR_ID VARCHAR2(64 BYTE) 
, EXTENSION VARCHAR2(2000 BYTE) 
, MEMO VARCHAR2(256 BYTE) 
) 


TRUNCATE TABLE K_TRADE_ODS.TSS_PAYMENT_ORDER_INC;
INSERT /*+ append nologging */ INTO K_TRADE_ODS.TSS_PAYMENT_ORDER_INC
SELECT *
FROM tss.T_PAYMENT_ORDER@kjtdb  
WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;

COMMIT;

DELETE FROM  K_TRADE.DWD_TSS_PAYMENT_ORDER_D WHERE GMT_CREATE >= last_day(add_months(trunc(sysdate),-2)) +1;
 
INSERT /*+   nologging */ INTO K_TRADE.DWD_TSS_PAYMENT_ORDER_D
SELECT 
	  t.*
	  ,sysdate DW_CREATE_TIME
	  ,sysdate DW_MODIFIED_TIME
FROM K_TRADE_ODS.TSS_PAYMENT_ORDER_INC t;


