CREATE TABLE K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC 
(
  TRADE_VOUCHER_NO VARCHAR2(32 BYTE) 
, BIZ_PRODUCT_CODE VARCHAR2(16 BYTE) 
, AMOUNT NUMBER(15, 2) 
, ACCESS_CHANNEL VARCHAR2(16 BYTE) 
, GMT_SUBMIT TIMESTAMP(6) 
, TRADE_STATUS VARCHAR2(16 BYTE) NOT NULL 
, GMT_CREATE TIMESTAMP(6) NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) 
, BIZNO VARCHAR2(32 BYTE)
) 
 
 
COMMENT ON TABLE K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC IS '充值交易订单';
COMMENT ON COLUMN K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC.TRADE_VOUCHER_NO IS '交易凭证号，主键，统一凭证';
COMMENT ON COLUMN K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC.BIZ_PRODUCT_CODE IS '产品编码';
COMMENT ON COLUMN K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC.AMOUNT IS '交易金额';
COMMENT ON COLUMN K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC.ACCESS_CHANNEL IS '终端类型';
COMMENT ON COLUMN K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC.GMT_SUBMIT IS '交易发起时间';
COMMENT ON COLUMN K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC.TRADE_STATUS IS '交易状态';
COMMENT ON COLUMN K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN K_TRADE_ODS.ODS_DEPOSIT_ORDER_INC.GMT_MODIFIED IS '修改时间';


