CREATE TABLE K_LKP.CMF_ORDER_STATUS_REMARK
(
	STATUS_CODE char
	,REMARK varchar2(50)
	,DW_CREATE_TIME date
	,DW_MODIFIED_TIME date
)
COMMENT ON TABLE K_LKP.CMF_ORDER_STATUS_REMARK IS '渠道路由订单状态'

COMMENT ON COLUMN K_LKP.CMF_ORDER_STATUS_REMARK.STATUS_CODE IS '状态编码';
COMMENT ON COLUMN K_LKP.CMF_ORDER_STATUS_REMARK.REMARK IS '状态描述';
COMMENT ON COLUMN K_LKP.CMF_ORDER_STATUS_REMARK.DW_CREATE_TIME IS '创建时间';
COMMENT ON COLUMN K_LKP.CMF_ORDER_STATUS_REMARK.DW_MODIFIED_TIME IS '更新时间';


