CREATE TABLE K_LKP.INST_ORDER_COMMUNICATE_TYPE
(
	COMMUNICATE_TYPE CHAR NOT NULL PRIMARY KEY
	,REMARK VARCHAR2(50)
	,DW_CREATE_TIME DATE
	,DW_MODIFIED_TIME DATE
);


COMMENT ON TABLE K_LKP.INST_ORDER_COMMUNICATE_TYPE IS '机构订单会话方式';

COMMENT ON COLUMN K_LKP.INST_ORDER_COMMUNICATE_TYPE.COMMUNICATE_TYPE IS '会话方式编码';
COMMENT ON COLUMN K_LKP.INST_ORDER_COMMUNICATE_TYPE.REMARK IS '会话方式描述';
COMMENT ON COLUMN K_LKP.INST_ORDER_COMMUNICATE_TYPE.DW_CREATE_TIME IS '创建时间';
COMMENT ON COLUMN K_LKP.INST_ORDER_COMMUNICATE_TYPE.DW_MODIFIED_TIME IS '更新时间';