package com.banggo.scheduler.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.SqlMapClientTemplate;

import com.banggo.scheduler.dao.daointerface.ScheUserGroupDAO;
import com.banggo.scheduler.dao.dataobject.ScheUserGroup;

public class ScheUserGroupDAOImpl implements ScheUserGroupDAO {
	private SqlMapClientTemplate sqlMapClient;

	public void setSqlMapClient(SqlMapClientTemplate sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int insert(ScheUserGroup record) throws DataAccessException {
    	Integer pk = (Integer) sqlMapClient.insert("SCHE_USER_GROUP.insert", record);
		return pk == null ? -1 : pk.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int updateByPrimaryKey(ScheUserGroup record) throws DataAccessException {
        int rows = sqlMapClient.update("SCHE_USER_GROUP.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int updateByPrimaryKeySelective(ScheUserGroup record) throws DataAccessException {
        int rows = sqlMapClient.update("SCHE_USER_GROUP.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public ScheUserGroup selectByPrimaryKey(Integer id) throws DataAccessException {
        ScheUserGroup key = new ScheUserGroup();
        key.setId(id);
        ScheUserGroup record = (ScheUserGroup) sqlMapClient.queryForObject("SCHE_USER_GROUP.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) throws DataAccessException {
        ScheUserGroup key = new ScheUserGroup();
        key.setId(id);
        int rows = sqlMapClient.delete("SCHE_USER_GROUP.deleteByPrimaryKey", key);
        return rows;
    }
    
    @Override
	public List<ScheUserGroup> select(Map params) {
		return sqlMapClient.queryForList("SCHE_USER_GROUP.select", params);
	}

	@Override
	public int count(Map params) {
		Integer count = (Integer) sqlMapClient.queryForObject("SCHE_USER_GROUP.count", params);
		return  count != null? count.intValue() : 0;
	}
}