package com.banggo.scheduler.dao.dataobject;

public class ScheJobParams {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_JOB_PARAMS.ID
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_JOB_PARAMS.SCHE_JOB_ID
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    private Integer scheJobId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_JOB_PARAMS.NAME
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_JOB_PARAMS.VALUE
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    private String value;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_JOB_PARAMS.ID
     *
     * @return the value of SCHE_JOB_PARAMS.ID
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_JOB_PARAMS.ID
     *
     * @param id the value for SCHE_JOB_PARAMS.ID
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_JOB_PARAMS.SCHE_JOB_ID
     *
     * @return the value of SCHE_JOB_PARAMS.SCHE_JOB_ID
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    public Integer getScheJobId() {
        return scheJobId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_JOB_PARAMS.SCHE_JOB_ID
     *
     * @param scheJobId the value for SCHE_JOB_PARAMS.SCHE_JOB_ID
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    public void setScheJobId(Integer scheJobId) {
        this.scheJobId = scheJobId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_JOB_PARAMS.NAME
     *
     * @return the value of SCHE_JOB_PARAMS.NAME
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_JOB_PARAMS.NAME
     *
     * @param name the value for SCHE_JOB_PARAMS.NAME
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_JOB_PARAMS.VALUE
     *
     * @return the value of SCHE_JOB_PARAMS.VALUE
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_JOB_PARAMS.VALUE
     *
     * @param value the value for SCHE_JOB_PARAMS.VALUE
     *
     * @abatorgenerated Sat Mar 31 17:25:39 CST 2012
     */
    public void setValue(String value) {
        this.value = value;
    }
}