package com.banggo.scheduler.dao.dataobject;

import java.util.Date;
import java.util.List;

public class ScheUserGroup {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER_GROUP.ID
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER_GROUP.NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER_GROUP.CREATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER_GROUP.CREATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER_GROUP.UPDATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private Date updateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER_GROUP.UPDATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String updateBy;
    
    private List<ScheUserGroupMember> scheUserGroupMemberList;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER_GROUP.ID
     *
     * @return the value of SCHE_USER_GROUP.ID
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER_GROUP.ID
     *
     * @param id the value for SCHE_USER_GROUP.ID
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER_GROUP.NAME
     *
     * @return the value of SCHE_USER_GROUP.NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER_GROUP.NAME
     *
     * @param name the value for SCHE_USER_GROUP.NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER_GROUP.CREATE_DATE
     *
     * @return the value of SCHE_USER_GROUP.CREATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER_GROUP.CREATE_DATE
     *
     * @param createDate the value for SCHE_USER_GROUP.CREATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER_GROUP.CREATE_BY
     *
     * @return the value of SCHE_USER_GROUP.CREATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER_GROUP.CREATE_BY
     *
     * @param createBy the value for SCHE_USER_GROUP.CREATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER_GROUP.UPDATE_DATE
     *
     * @return the value of SCHE_USER_GROUP.UPDATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER_GROUP.UPDATE_DATE
     *
     * @param updateDate the value for SCHE_USER_GROUP.UPDATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER_GROUP.UPDATE_BY
     *
     * @return the value of SCHE_USER_GROUP.UPDATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER_GROUP.UPDATE_BY
     *
     * @param updateBy the value for SCHE_USER_GROUP.UPDATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

	public List<ScheUserGroupMember> getScheUserGroupMemberList() {
		return scheUserGroupMemberList;
	}

	public void setScheUserGroupMemberList(
			List<ScheUserGroupMember> scheUserGroupMemberList) {
		this.scheUserGroupMemberList = scheUserGroupMemberList;
	}
}