package com.banggo.scheduler.dao.dataobject;

import java.util.Date;

public class ScheUser {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.ID
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.EMAIL
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.MOBILE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.USER_NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String userName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.CREATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.CREATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.UPDATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private Date updateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCHE_USER.UPDATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    private String updateBy;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.ID
     *
     * @return the value of SCHE_USER.ID
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.ID
     *
     * @param id the value for SCHE_USER.ID
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.EMAIL
     *
     * @return the value of SCHE_USER.EMAIL
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.EMAIL
     *
     * @param email the value for SCHE_USER.EMAIL
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.MOBILE
     *
     * @return the value of SCHE_USER.MOBILE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.MOBILE
     *
     * @param mobile the value for SCHE_USER.MOBILE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.USER_NAME
     *
     * @return the value of SCHE_USER.USER_NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.USER_NAME
     *
     * @param userName the value for SCHE_USER.USER_NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.NAME
     *
     * @return the value of SCHE_USER.NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.NAME
     *
     * @param name the value for SCHE_USER.NAME
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.CREATE_DATE
     *
     * @return the value of SCHE_USER.CREATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.CREATE_DATE
     *
     * @param createDate the value for SCHE_USER.CREATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.CREATE_BY
     *
     * @return the value of SCHE_USER.CREATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.CREATE_BY
     *
     * @param createBy the value for SCHE_USER.CREATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.UPDATE_DATE
     *
     * @return the value of SCHE_USER.UPDATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.UPDATE_DATE
     *
     * @param updateDate the value for SCHE_USER.UPDATE_DATE
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCHE_USER.UPDATE_BY
     *
     * @return the value of SCHE_USER.UPDATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCHE_USER.UPDATE_BY
     *
     * @param updateBy the value for SCHE_USER.UPDATE_BY
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
}