CREATE TABLE K_CHANNEL.DIM_FUND_CHANNEL_EXT_D (
	EXT_ID	NUMBER(11,0)
	,FUND_CHANNEL_CODE	VARCHAR2(32 BYTE)
	,ATTR_KEY	VARCHAR2(32 BYTE)
	,ATTR_VALUE	VARCHAR2(2560 BYTE)
	,ATTR_TYPE	CHAR(1 BYTE)
	,VALUE_TYPE	VARCHAR2(32 BYTE)
	,VALUE_SPLIT	CHAR(1 BYTE)
	,GMT_CREATE	TIMESTAMP(6)
	,GMT_MODIFIED	TIMESTAMP(6)
	,MEMO	VARCHAR2(128 BYTE)
	,ATTR_CODE_KEY	VARCHAR2(32 BYTE)
	,API_CODE	VARCHAR2(32 BYTE)
	,NEED_MATCH	CHAR(1 BYTE)
	,MATCH_TYPE	VARCHAR2(32 BYTE)
	,DW_CREATE_TIME DATE DEFAULT SYSDATE
	,DW_MODIFIED_TIME DATE 
);

COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.EXT_ID IS '扩展ID';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.FUND_CHANNEL_CODE IS '资金源编码';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.ATTR_KEY IS '属性名';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.ATTR_VALUE IS '属性值';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.ATTR_TYPE IS '属性类型：N（无特殊制定），F（流量）';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.VALUE_TYPE IS '值类型';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.VALUE_SPLIT IS '值分隔符，针对有多选属性使用';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.GMT_MODIFIED IS '最后修改时间';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.MEMO IS '备注';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.ATTR_CODE_KEY IS '属性字典标识';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.API_CODE IS 'api编码';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.NEED_MATCH IS '是否需要满足VALUE指定';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.MATCH_TYPE IS '比较类型';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.DW_CREATE_TIME IS '数仓创建时间';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_EXT_D.DW_MODIFIED_TIME. IS '数仓更新时间';