CREATE TABLE K_CHANNEL.DIM_FUND_CHANNEL_D 
(
  FUND_CHANNEL_CODE VARCHAR2(32 BYTE) NOT NULL 
, NAME VARCHAR2(64 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(256 BYTE) 
, INST_CODE VARCHAR2(16 BYTE) NOT NULL 
, BIZ_TYPE CHAR(1 BYTE) NOT NULL 
, PAY_MODE VARCHAR2(16 BYTE) NOT NULL 
, SIGNED_CROP CHAR(1 BYTE) NOT NULL 
, STATUS VARCHAR2(16 BYTE) NOT NULL 
, VALID_FROM TIMESTAMP(6) NOT NULL 
, VALID_TO TIMESTAMP(6) NOT NULL 
, MAX_AMOUNT NUMBER(15, 2) NOT NULL 
, MIN_AMOUNT NUMBER(15, 2) NOT NULL 
, EXPECT_ARRIVE_TIME VARCHAR2(16 BYTE) NOT NULL 
, GMT_CREATE TIMESTAMP(6) NOT NULL 
, GMT_MODIFIED TIMESTAMP(6) NOT NULL 
, MEMO VARCHAR2(128 BYTE) 
, CHANNEL_MODE VARCHAR2(16 BYTE) 
, PRIORITY NUMBER(2, 0)
, DW_CREATE_TIME DATE DEFAULT SYSDATE
, DW_MODIFIED_TIME DATE DEFAULT SYSDATE
)
;



COMMENT ON TABLE K_CHANNEL.DIM_FUND_CHANNEL_D IS '资金渠道';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.FUND_CHANNEL_CODE IS '编码';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.NAME IS '名称';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.DESCRIPTION IS '描述';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.INST_CODE IS '机构代码';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.BIZ_TYPE IS '业务类型：I（入款），O（出款）';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.PAY_MODE IS '支付方式，如：网银，卡通，线下，手机充值卡，手机话费，微汇卡，积分。。。';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.SIGNED_CROP IS '签约公司：Y（益充），S（微汇）';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.STATUS IS '是否可用：VALID（可用），INVALID（不可用）';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.EXPECT_ARRIVE_TIME IS 'T+15M表示15分钟到帐，T+1D表示一天到帐，H小时';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.GMT_MODIFIED IS '最后修改时间';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.MEMO IS '备注';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.PRIORITY IS '此优先级在过滤，优选之后使用';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.DW_CREATE_TIME IS 'DW 创建时间';
COMMENT ON COLUMN K_CHANNEL.DIM_FUND_CHANNEL_D.DW_MODIFIED_TIME IS 'DW 更新时间';