-- 这个表走 DBLINK   访问会报 cannot use LOB locators selected from remote tables
-- 经验证 灾备库 中数据 与 BIPAY.S_CMF_TM_FUND_CHANNEL_TARGET_I  一致，首次就从 BIPAY.S_CMF_TM_FUND_CHANNEL_TARGET_I 抽取
INSERT INTO K_CHANNEL.DIM_FUND_CHANNEL_TARGET_INST_D

SELECT
S0.*
,SYSDATE DW_CREATE_TIME
,SYSDATE DW_MODIFIED_TIME
FROM BIPAY.S_CMF_TM_FUND_CHANNEL_TARGET_I S0
;


COMMIT;


SELECT
*
FROM  K_CHANNEL.DIM_FUND_CHANNEL_TARGET_INST_D