CREATE TABLE K_CHANNEL.DWD_REFUND_ORDER_D 
(
	INST_ORDER_ID	NUMBER(15,0)
	,FUNDIN_ORDER_NO	VARCHAR2(32 BYTE)
	,FUNDIN_REAL_AMOUNT	NUMBER(15,2)
	,FUNDIN_DATE	VARCHAR2(16 BYTE)
	,GMT_MODIFIED	TIMESTAMP(6)
	,DW_CREATE_TIME DATE DEFAULT SYSDATE
	,DW_MODIFIED_TIME DATE DEFAULT SYSDATE
)
;

COMMENT ON COLUMN K_CHANNEL.DWD_REFUND_ORDER_D.INST_ORDER_ID IS '机构订单ID';
COMMENT ON COLUMN K_CHANNEL.DWD_REFUND_ORDER_D.FUNDIN_ORDER_NO IS '充值订单号';
COMMENT ON COLUMN K_CHANNEL.DWD_REFUND_ORDER_D.FUNDIN_REAL_AMOUNT	IS '充值实收金额';
COMMENT ON COLUMN K_CHANNEL.DWD_REFUND_ORDER_D.FUNDIN_DATE  IS '入款时间';
COMMENT ON COLUMN K_CHANNEL.DWD_REFUND_ORDER_D.GMT_MODIFIED IS '最后修改时间';
COMMENT ON COLUMN K_CHANNEL.DWD_REFUND_ORDER_D.DW_CREATE_TIME  IS 'DW 创建时间';
COMMENT ON COLUMN K_CHANNEL.DWD_REFUND_ORDER_D.DW_MODIFIED_TIME IS 'DW 更新时间';