CREATE TABLE K_CHANNEL.DIM_FUND_CHANNEL_TARGET_INST_D
(
	TARGET_INST_CODE	VARCHAR2(16 BYTE)
	,SHORT_NAME	VARCHAR2(20 BYTE)
	,TARGET_INST_NAME	VARCHAR2(50 BYTE)
	,TARGET_INST_DESC	VARCHAR2(256 BYTE)
	,ICON_URL	VARCHAR2(256 BYTE)
	,AMOUNT_LIMIT_DESC	CLOB
	,GMT_CREATE	TIMESTAMP(6)
	,GMT_MODIFIED	TIMESTAMP(6)
	,DW_CREATE_TIME DATE DEFAULT SYSDATE
	,DW_MODIFIED_TIME DATE DEFAULT SYSDATE
)
;


