INSERT INTO K_CHANNEL.DWD_FUND_CHANNEL_ORDER_D

SELECT
S0.CMF_SEQ_NO
,S0.PAYMENT_SEQ_NO
,S0.ORDER_TYPE
,S0.PRODUCT_CODE
,S0.PAYMENT_CODE
,S0.MEMBER_ID
,S0.AMOUNT
,S0.CURRENCY
,S0.INST_CODE TARGET_INST_CODE
,S0.PAYMENT_NOTIFY_STATUS
,S0.STATUS CMF_ORDER_STATUS
,S0.INST_ORDER_ID
,S0.BIZ_DATE
,S0.GMT_CREATE
,S0.GMT_MODIFIED
,S0.CONFIRM_STATUS
,S0.PAY_MODE DECLARE_PAY_MODE
,S0.SETTLEMENT_ID
,S1.INST_ORDER_NO
,S1.STATUS INST_ORDER_STATUS
,S1.COMMUNICATE_TYPE
,S1.COMMUNICATE_STATUS
,S1.GMT_MODIFIED INST_ORDER_MODIFIED_TIME
,S1.MEMO
,S1.FUND_CHANNEL_CODE
,S1.FUND_CHANNEL_API
,S1.FLAG
,S2.FUND_CHANNEL_NAME
,S2.FUND_CHANNEL_DES
,S2.FUND_CHANNEL_INST_CODE
,S2.PAY_MODE REAL_PAY_MODE
,S2.IS_BFJ
,S2.CONNECTTYPE
,SYSDATE DW_CREATE_TIME
,SYSDATE DW_MODIFIED_TIME
FROM K_CHANNEL.DWD_CMF_ORDER_D S0
INNER JOIN K_CHANNEL.DWD_INST_ORDER_D S1
ON S0.INST_ORDER_ID=S1.INST_ORDER_ID
LEFT JOIN K_CHANNEL.DIM_BANK_FUND_CHANNEL_D S2
ON S1.FUND_CHANNEL_CODE=S2.FUND_CHANNEL_CODE
;


-----
SELECT
S0.CMF_SEQ_NO
,S0.PAYMENT_SEQ_NO
,S0.ORDER_TYPE 
,S0.PRODUCT_CODE
,S0.PAYMENT_CODE 
,S0.MEMBER_ID
,S0.AMOUNT
,S0.CURRENCY
,S0.INST_CODE TARGET_INST_CODE
,S5.TARGET_INST_NAME
,S0.PAYMENT_NOTIFY_STATUS
,S0.STATUS CMF_ORDER_STATUS
,S0.INST_ORDER_ID
,S0.BIZ_DATE
,S0.GMT_CREATE
,S0.GMT_MODIFIED
,S0.CONFIRM_STATUS
,S0.PAY_MODE DECLARE_PAY_MODE_CODE
,S3.REMARK  DECLARE_PAY_MODE_NAME
,S0.SETTLEMENT_ID
,S1.INST_ORDER_NO
,S1.STATUS INST_ORDER_STATUS
,S1.COMMUNICATE_TYPE
,S1.COMMUNICATE_STATUS
,S1.GMT_MODIFIED INST_ORDER_MODIFIED_TIME
,S1.MEMO
,S1.FUND_CHANNEL_CODE
,S1.FUND_CHANNEL_API
,S1.FLAG
,S2.FUND_CHANNEL_NAME
,S2.FUND_CHANNEL_DES
,S2.FUND_CHANNEL_INST_CODE
,S2.PAY_MODE REAL_PAY_MODE_CODE
,S4.REMARK REAL_PAY_MODE_NAME
,S2.IS_BFJ
,S2.CONNECTTYPE
,SYSDATE DW_CREATE_TIME
,SYSDATE DW_MODIFIED_TIME
FROM K_CHANNEL.DWD_CMF_ORDER_D S0
INNER JOIN K_CHANNEL.DWD_INST_ORDER_D S1
ON S0.INST_ORDER_ID=S1.INST_ORDER_ID
LEFT JOIN K_CHANNEL.DIM_BANK_FUND_CHANNEL_D S2
ON S1.FUND_CHANNEL_CODE=S2.FUND_CHANNEL_CODE
LEFT JOIN K_LKP.PAY_MODE S3
ON S0.PAY_MODE=S3.PAY_MODE
LEFT JOIN K_LKP.PAY_MODE S4
ON S2.PAY_MODE=S4.PAY_MODE
LEFT JOIN K_CHANNEL.DIM_FUND_CHANNEL_TARGET_INST_D S5
ON S0.INST_CODE=S5.TARGET_INST_CODE
;

