package com.banggo.scheduler.dao.ibatis;

import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.SqlMapClientTemplate;

import com.banggo.scheduler.dao.daointerface.ScheUserGroupMemberDAO;
import com.banggo.scheduler.dao.dataobject.ScheUserGroupMember;

public class ScheUserGroupMemberDAOImpl implements ScheUserGroupMemberDAO {
	private SqlMapClientTemplate sqlMapClient;

	public void setSqlMapClient(SqlMapClientTemplate sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP_MEMBER
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public void insert(ScheUserGroupMember record) throws DataAccessException {
        sqlMapClient.insert("SCHE_USER_GROUP_MEMBER.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP_MEMBER
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int updateByPrimaryKey(ScheUserGroupMember record) throws DataAccessException {
        int rows = sqlMapClient.update("SCHE_USER_GROUP_MEMBER.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP_MEMBER
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int updateByPrimaryKeySelective(ScheUserGroupMember record) throws DataAccessException {
        int rows = sqlMapClient.update("SCHE_USER_GROUP_MEMBER.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP_MEMBER
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public ScheUserGroupMember selectByPrimaryKey(Integer id) throws DataAccessException {
        ScheUserGroupMember key = new ScheUserGroupMember();
        key.setId(id);
        ScheUserGroupMember record = (ScheUserGroupMember) sqlMapClient.queryForObject("SCHE_USER_GROUP_MEMBER.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCHE_USER_GROUP_MEMBER
     *
     * @abatorgenerated Thu Nov 15 14:34:17 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) throws DataAccessException {
        ScheUserGroupMember key = new ScheUserGroupMember();
        key.setId(id);
        int rows = sqlMapClient.delete("SCHE_USER_GROUP_MEMBER.deleteByPrimaryKey", key);
        return rows;
    }
    
    public int deleteByGroupId(Integer groupId) throws DataAccessException {
    	int rows = sqlMapClient.delete("SCHE_USER_GROUP_MEMBER.deleteByGroupId", groupId);
    	return rows;
    }
}