SELECT
TO_CHAR(S0.GMT_CREATE,'YYYYMMDD') DATE_KEY
,S0.INST_ORDER_ID ORDER_ID
,S0.INST_CODE
,S2.TARGET_INST_NAME INST_NAME
,S2.SHORT_NAME INST_SHORT_NAME
,S0.ORDER_TYPE ORDER_TYPE_CODE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'ORDER_TYPE' AND field_key = S0.ORDER_TYPE AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护支付渠道交易类型') as ORDER_TYPE_NAME
,S0.CURRENCY CURRENCY_CODE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'CURRENCY' AND field_key = S0.CURRENCY AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护支付渠道币种') as CURRENCY_NAME
,S0.AMOUNT
,S0.STATUS STATUS_CODE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'STATUS' AND field_key = S0.STATUS AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护渠道INST订单状态') as STATUS_NAME
,S0.GMT_CREATE order_create_time
,S0.GMT_submit order_submit_time
,S0.GMT_MODIFIED order_modified_time
,S0.PRODUCT_CODE
,NVL(S4.DES,'联系BI维护新的产品码') PRODUCT_NAME
,S0.PAYMENT_CODE
,S0.PAY_MODE DECLARE_PAY_MODE_CODE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'PAY_MODE' AND field_key = S0.PAY_MODE AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护渠道支付方式') as DECLARE_PAY_MODE_NAME
,S3.PAY_MODE REAL_PAY_MODE_CODE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'PAY_MODE' AND field_key = S3.PAY_MODE AND table_name = 'S_CMF_TM_FUND_CHANNEL'),'联系BI维护渠道支付方式') as REAL_PAY_MODE_NAME
,S0.FUND_CHANNEL_CODE
,S3.NAME  FUND_CHANNEL_NAME
,S5.connecttype FUND_CONNECT_TYPE
,S0.COMMUNICATE_TYPE COMMUNICATE_TYPE_CODE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'COMMUNICATE_TYPE' AND field_key = S0.COMMUNICATE_TYPE AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护渠道风控状态') as COMMUNICATE_TYPE_NAME
,S0.FUND_CHANNEL_API
,S0.RISK_STATUS RISK_STATUS_CODE
,DECODE(S0.RISK_STATUS,NULL,NULL,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'RISK_STATUS' AND field_key = S0.RISK_STATUS AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护渠道风控状态')) as RISK_STATUS_NAME
FROM BIPAY.S_CMF_TT_INST_ORDER S0
LEFT JOIN BIPAY.S_CMF_TM_FUND_CHANNEL_TARGET_I S2
ON S0.INST_CODE=S2.TARGET_INST_CODE
LEFT JOIN BIPAY.S_CMF_TM_FUND_CHANNEL S3
ON S0.FUND_CHANNEL_CODE=S3.FUND_CHANNEL_CODE
LEFT JOIN BIDIM.OBJ_PAY_PRODUCT S4
ON S0.PRODUCT_CODE=S4.PRODUCT_CODE
LEFT JOIN BIDIM.OBJ_PAY_FUND_CHANNEL_CONNECT S5
ON S0.FUND_CHANNEL_CODE=S5.FUND_CHANNEL_CODE