CREATE TABLE DW_PAY_CHANNEL_FACT 
(
  DATE_KEY NUMBER 
, ORDER_ID VARCHAR2(20 BYTE) 
, INST_CODE VARCHAR2(10 BYTE) 
, INST_NAME VARCHAR2(200 BYTE) 
, INST_SHORT_NAME VARCHAR2(200 BYTE) 
, ORDER_TYPE_CODE VARCHAR2(5 BYTE) 
, ORDER_TYPE_NAME VARCHAR2(20 BYTE) 
, CURRENCY_CODE VARCHAR2(10 BYTE) NOT NULL 
, CURRENCY_NAME VARCHAR2(20 BYTE) 
, AMOUNT VARCHAR2(20 BYTE) 
, STATUS_CODE VARCHAR2(20 BYTE) 
, STATUS_NAME VARCHAR2(20 BYTE) 
, ORDER_CREATE_TIME DATE 
, ORDER_SUBMIT_TIME DATE 
, ORDER_MODIFIED_TIME DATE 
, PRODUCT_CODE VARCHAR2(20 BYTE) 
, PAYMENT_CODE VARCHAR2(20 BYTE) 
, DECLARE_PAY_MODE_CODE VARCHAR2(20 BYTE) 
, DECLARE_PAY_MODE_NAME VARCHAR2(50 BYTE) 
, REAL_PAY_MODE_CODE VARCHAR2(20 BYTE) 
, REAL_PAY_MODE_NAME VARCHAR2(50 BYTE) 
, FUND_CHANNEL_CODE VARCHAR2(20 BYTE) 
, FUND_CHANNEL_NAME VARCHAR2(200 BYTE) 
, FUND_CONNECT_TYPE VARCHAR2(20 BYTE)
, COMMUNICATE_TYPE_CODE VARCHAR2(20 BYTE) 
, COMMUNICATE_TYPE_NAME VARCHAR2(20 BYTE) 
, FUND_CHANNEL_API VARCHAR2(50 BYTE) 
, RISK_STATUS_CODE VARCHAR2(50 BYTE) 
, RISK_STATUS_NAME VARCHAR2(100 BYTE) 
) 

PARTITION BY RANGE (ORDER_CREATE_TIME) 
INTERVAL(NUMTOYMINTERVAL(1，'MONTH')) 
(
  PARTITION P_MONTH_1 VALUES LESS THAN (TO_DATE('2015-01-01', 'YYYY-MM-DD')）
)
;

COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.DATE_KEY IS '订单创建日期';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.ORDER_ID IS '订单ID';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.INST_CODE IS '机构编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.INST_NAME IS '机构名称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.INST_SHORT_NAME IS '机构简称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.ORDER_TYPE_CODE IS '交易类型编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.ORDER_TYPE_NAME IS '交易类型名称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.CURRENCY_CODE IS '币种编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.CURRENCY_NAME IS '币种名称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.AMOUNT IS '交易金额';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.STATUS_CODE IS '订单状态编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.STATUS_NAME IS '订单状态名称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.ORDER_CREATE_TIME IS '订单创建时间';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.ORDER_SUBMIT_TIME IS '订单提交时间';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.ORDER_MODIFIED_TIME IS '订单修改时间';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.DECLARE_PAY_MODE_CODE IS '宣称支付模式编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.DECLARE_PAY_MODE_NAME IS '宣称支付模式名称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.REAL_PAY_MODE_CODE IS '真实支付模式编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.REAL_PAY_MODE_NAME IS '真实支付模式名称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.FUND_CHANNEL_CODE IS '资金渠道编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.FUND_CHANNEL_NAME IS '资金渠道名称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.FUND_CONNECT_TYPE IS '连接类型';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.COMMUNICATE_TYPE_CODE IS '会话类型编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.COMMUNICATE_TYPE_NAME IS '会话类型名称';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.FUND_CHANNEL_API IS '资金渠道API';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.RISK_STATUS_CODE IS '风控状态编码';
COMMENT ON COLUMN DW_PAY_CHANNEL_FACT.RISK_STATUS_NAME IS '风控状态';
