SELECT
T0.MEMBER_ID
,T0.MEMBER_TYPE MEMBER_TYPE_CODE
,DECODE(T0.MEMBER_TYPE,1,'个人',2,'企业',3,'商户') MEMBER_TYPE_NAME
,T1.CERT_TYPE REAL_NAME_CERT_TYPE
,T1.AUTH_NAME REAL_NAME_AUTH_NAME
,T1.STATUS REAL_NAME_STATUS_CODE
,DECODE(T1.STATUS,1,'有效')REAL_NAME_AUTH_STATUS_NAME
,T1.HANG_STATUS REAL_NAME_HANG_STATUS_CODE
,T2.CERT_TYPE IDENTITY_CERT_TYPE
,T2.AUTH_NAME IDENTITY_AUTH_NAME
,T2.STATUS IDENTITY_STATUS_CODE
,DECODE(T2.STATUS,1,'有效') IDENTITY_STATUS_NAME
FROM MEMBER.TM_MEMBER@KJTDB T0
LEFT JOIN cert.tt_auth_info@KJTDB T1
ON T0.MEMBER_ID=T1.MEMBER_ID
LEFT JOIN cert.tt_auth_info@KJTDB T2
ON T0.MEMBER_ID=T2.MEMBER_ID
WHERE T1.AUTH_TYPE='realName' 
AND T2.AUTH_TYPE='identity' 
AND T0.MEMBER_TYPE=2
;