CREATE TABLE K_USER.DIM_BUSINESS_MEMBEER_TAG 
 (  
  MEMBER_ID VARCHAR2(32 BYTE) NOT NULL PRIMARY KEY, 
 LOGIN_NAME VARCHAR2(50 BYTE), 
 MEMBER_NAME VARCHAR2(255 BYTE), 
 MEMBER_DES VARCHAR2(255 BYTE), 
 BD_OWNER_NAME VARCHAR2(50 BYTE), 
 BD_OWNER_MAIL VARCHAR2(50 BYTE), 
 IS_NEED_INVOICE VARCHAR2(10 BYTE),
 ECOLOGY_TYPE VARCHAR2(50 BYTE),
 GROUP_TYPE  VARCHAR2(50 BYTE),
 PROJECT_TYPE VARCHAR2(50 BYTE),
 SETTLE_TYPE  VARCHAR2(50 BYTE),
 DW_CREATE_TIME DATE DEFAULT SYSDATE, 
 DW_MODIFIED_TIME DATE DEFAULT SYSDATE
 )
 ;
 COMMENT ON TABLE K_USER.DIM_BUSINESS_MEMBEER_TAG  IS '商户和企业会员标签';

 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.MEMBER_ID IS '会员ID';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.LOGIN_NAME IS '会员登录名称';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.MEMBER_NAME IS '会员名称';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.MEMBER_DES IS '会员描述（会员名称和会员登录名拼接而成)';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.BD_OWNER_NAME IS 'BD 对接人名称';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.BD_OWNER_MAIL IS 'BD 对接人邮箱';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.IS_NEED_INVOICE IS '是否需要开具发票';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.ECOLOGY_TYPE IS '生态类型';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.GROUP_TYPE IS '集团类型';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.PROJECT_TYPE IS '项目类型';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.SETTLE_TYPE IS '结算类型';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.DW_CREATE_TIME IS '创建时间';
 COMMENT ON COLUMN K_USER.DIM_BUSINESS_MEMBEER_TAG.DW_MODIFIED_TIME IS '更新时间';