------ 出款



insert into BIPAY.DW_PAY_CHANNEL_OUT_FACT
SELECT
TO_CHAR(S0.GMT_MODIFIED,'YYYYMMDD') DATE_KEY
,S0.INST_ORDER_ID
,CO.MEMBER_ID
,PO.PAYMENT_ORDER_NO PAYMENT_VOUCHER_NO
,S0.INST_CODE
,S1.TARGET_INST_NAME INST_NAME
,S1.SHORT_NAME INST_SHORT_NAME
,S0.CURRENCY
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'CURRENCY' AND field_key = S0.CURRENCY AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护支付渠道币种') as CURRENCY_NAME
,S0.AMOUNT
,S0.STATUS
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'STATUS' AND field_key = S0.STATUS AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护渠道INST订单状态') as STATUS_NAME
,S0.GMT_CREATE 
,S0.GMT_submit 
,S0.GMT_MODIFIED
,S0.PRODUCT_CODE
,S0.PAYMENT_CODE
,S0.PAY_MODE DECLARE_PAY_MODE_CODE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'PAY_MODE' AND field_key = S0.PAY_MODE AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护渠道支付方式') as DECLARE_PAY_MODE_NAME
,S2.PAY_MODE REAL_PAY_MODE_CODE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'PAY_MODE' AND field_key = S2.PAY_MODE AND table_name = 'S_CMF_TM_FUND_CHANNEL'),'联系BI维护渠道支付方式') as REAL_PAY_MODE_NAME
,S0.FUND_CHANNEL_CODE
,S2.NAME  FUND_CHANNEL_NAME
,S0.COMMUNICATE_TYPE
,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'COMMUNICATE_TYPE' AND field_key = S0.COMMUNICATE_TYPE AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护渠道风控状态') as COMMUNICATE_TYPE_NAME
,S5.connecttype FUND_CONNECT_TYPE
,S0.FUND_CHANNEL_API
,S0.RISK_STATUS RISK_STATUS_CODE
,DECODE(S0.RISK_STATUS,NULL,NULL,NVL((SELECT field_value FROM BIDIM.FIELD_META_PAY WHERE field_name = 'RISK_STATUS' AND field_key = S0.RISK_STATUS AND table_name = 'S_CMF_TT_INST_ORDER'),'联系BI维护渠道风控状态')) as RISK_STATUS_NAME
,DECODE(S6.fund_channel_code,NULL,'外部营收','内部调拨') FUND_OUT_TYPE
FROM BIPAY.S_CMF_TT_INST_ORDER S0
LEFT JOIN BIPAY.S_CMF_TM_FUND_CHANNEL_TARGET_I S1
ON S0.INST_CODE=S1.TARGET_INST_CODE
LEFT JOIN BIPAY.S_CMF_TM_FUND_CHANNEL S2
ON S0.FUND_CHANNEL_CODE=S2.FUND_CHANNEL_CODE
LEFT JOIN BIPAY.S_CMF_TT_CMF_ORDER CO
ON S0.INST_ORDER_ID=CO.INST_ORDER_ID
LEFT JOIN BIPAY.S_PAT_TB_PAYMENT_ORDER PO
ON CO.PAYMENT_SEQ_NO=PO.PAYMENT_SEQ_NO
LEFT JOIN BIDIM.OBJ_PAY_FUND_CHANNEL_CONNECT S5
ON S0.FUND_CHANNEL_CODE=S5.FUND_CHANNEL_CODE
LEFT JOIN (
select
tx.fund_channel_code
from BIPAY.S_CMF_TM_FUND_CHANNEL_EXT tx
where tx.attr_key='businessType' and tx.attr_value='BFJ' and tx.match_type='in' and tx.need_match='Y'
group by tx.fund_channel_code
) S6
ON S0.FUND_CHANNEL_CODE=S6.FUND_CHANNEL_CODE
WHERE (
S0.GMT_MODIFIED >=TO_DATE('20170101','yyyymmdd') 
-- and 
--S0.GMT_MODIFIED <TO_DATE('20170101','yyyymmdd')
)
AND S0.ORDER_TYPE='O'
AND (S0.STATUS='S' OR S0.STATUS='F')
;
commit;