------ 入款
SELECT
TO_CHAR(S0.GMT_MODIFIED,'YYYYMMDD') DATE_KEY
,S0.INST_ORDER_ID
,CO.MEMBER_ID
,PO.PAYMENT_ORDER_NO PAYMENT_VOUCHER_NO
,S0.INST_CODE
,S1.TARGET_INST_NAME INST_NAME
,S1.SHORT_NAME INST_SHORT_NAME
,S0.CURRENCY
,S0.AMOUNT
,S0.STATUS
,S0.GMT_CREATE order_create_time
,S0.GMT_submit order_submit_time
,S0.GMT_MODIFIED order_modified_time
,S0.PRODUCT_CODE
,S0.PAYMENT_CODE
,S0.PAY_MODE DECLARE_PAY_MODE_CODE
,S2.PAY_MODE REAL_PAY_MODE_CODE
,S0.FUND_CHANNEL_CODE
,S2.NAME  FUND_CHANNEL_NAME
,S0.COMMUNICATE_TYPE
,S0.FUND_CHANNEL_API
,S0.RISK_STATUS RISK_STATUS_CODE
FROM CMF.TT_INST_ORDER S0
LEFT JOIN CMF.TM_FUND_CHANNEL_TARGET_INST S1
ON S0.INST_CODE=S1.TARGET_INST_CODE
LEFT JOIN CMF.TM_FUND_CHANNEL S2
ON S0.FUND_CHANNEL_CODE=S2.FUND_CHANNEL_CODE
LEFT JOIN CMF.TT_CMF_ORDER CO
ON S0.INST_ORDER_ID=CO.INST_ORDER_ID
LEFT JOIN PAYMENT.TB_PAYMENT_ORDER PO
ON CO.PAYMENT_SEQ_NO=PO.PAYMENT_SEQ_NO
WHERE S0.GMT_CREATE >TO_DATE('20170516','yyyymmdd')
AND S0.ORDER_TYPE='I'
AND (S0.STATUS='S' OR S0.STATUS='F')
;


------ 出款
SELECT
TO_CHAR(S0.GMT_MODIFIED,'YYYYMMDD') DATE_KEY
,S0.INST_ORDER_ID
,CO.MEMBER_ID
,PO.PAYMENT_ORDER_NO PAYMENT_VOUCHER_NO
,S0.INST_CODE
,S1.TARGET_INST_NAME INST_NAME
,S1.SHORT_NAME INST_SHORT_NAME
,S0.CURRENCY
,S0.AMOUNT
,S0.STATUS
,S0.GMT_CREATE order_create_time
,S0.GMT_submit order_submit_time
,S0.GMT_MODIFIED order_modified_time
,S0.PRODUCT_CODE
,S0.PAYMENT_CODE
,S0.PAY_MODE DECLARE_PAY_MODE_CODE
,S2.PAY_MODE REAL_PAY_MODE_CODE
,S0.FUND_CHANNEL_CODE
,S2.NAME  FUND_CHANNEL_NAME
,S0.COMMUNICATE_TYPE
,S0.FUND_CHANNEL_API
,S0.RISK_STATUS RISK_STATUS_CODE
FROM CMF.TT_INST_ORDER S0
LEFT JOIN CMF.TM_FUND_CHANNEL_TARGET_INST S1
ON S0.INST_CODE=S1.TARGET_INST_CODE
LEFT JOIN CMF.TM_FUND_CHANNEL S2
ON S0.FUND_CHANNEL_CODE=S2.FUND_CHANNEL_CODE
LEFT JOIN CMF.TT_CMF_ORDER CO
ON S0.INST_ORDER_ID=CO.INST_ORDER_ID
LEFT JOIN PAYMENT.TB_PAYMENT_ORDER PO
ON CO.PAYMENT_SEQ_NO=PO.PAYMENT_SEQ_NO
WHERE S0.GMT_CREATE >TO_DATE('20170516','yyyymmdd')
AND S0.ORDER_TYPE='O'
AND (S0.STATUS='S' OR S0.STATUS='F')
;