WITH TMP_DM AS (
SELECT
*
FROM BIPAY.DM_FUND_CHANNEL_IN_D S0
WHERE S0.DATE_KEY BETWEEN '20170401' AND '20170430'
AND S0.REAL_PAY_MODE_NAME='网银支付'
)



SELECT
S1.渠道编码
,S1.渠道名称
,S1.ORDER_COUNT_TOTAL  支付总笔数
,s1.ORDER_AMT_TOTAL 支付总金额
,S2.ORDER_COUNT_SUCCESS 支付成功笔数
,S2.ORDER_AMT_SUCCESS 支付成功金额
,(CASE WHEN S1.ORDER_COUNT_TOTAL=0 THEN 100
  ELSE ROUND(100*S2.ORDER_COUNT_SUCCESS/S1.ORDER_COUNT_TOTAL,2)
  END)||'%' 成功笔数占比
,(CASE
  WHEN S1.ORDER_AMT_TOTAL=0 THEN 100
  ELSE ROUND((100*S2.ORDER_AMT_SUCCESS/S1.ORDER_AMT_TOTAL),2)
END)||'%' 成功金额占比
FROM (
SELECT
'汇总' AS 渠道编码
,'汇总' AS 渠道名称
,SUM(S0.ORDER_COUNT) ORDER_COUNT_TOTAL
,SUM(S0.ORDER_AMT) ORDER_AMT_TOTAL
FROM TMP_DM S0
GROUP BY '汇总','汇总'
) S1
left join (
SELECT
'汇总' AS 渠道编码
,'汇总' AS 渠道名称
,SUM(S0.ORDER_COUNT) ORDER_COUNT_SUCCESS
,SUM(S0.ORDER_AMT) ORDER_AMT_SUCCESS
FROM TMP_DM S0
WHERE S0.STATUS_NAME ='成功'
GROUP BY '汇总','汇总'
) S2
ON S1.渠道编码=S2.渠道编码

UNION ALL

SELECT
S1.FUND_CHANNEL_CODE 渠道编码
,S1.FUND_CHANNEL_NAME 渠道名称
,S1.ORDER_COUNT_TOTAL 支付总笔数
,S1.ORDER_AMT_TOTAL 支付总金额
,NVL(S2.ORDER_COUNT_SUCCESS,0) 支付成功笔数 
,NVL(S2.ORDER_AMT_SUCCESS,0) 支付成功金额
,(CASE WHEN S1.ORDER_COUNT_TOTAL=0 THEN 100
  ELSE ROUND(100*S2.ORDER_COUNT_SUCCESS/S1.ORDER_COUNT_TOTAL,2)
  END)||'%' 成功笔数占比
,(CASE
  WHEN S1.ORDER_AMT_TOTAL=0 THEN 100
  ELSE ROUND(100*S2.ORDER_AMT_SUCCESS/S1.ORDER_AMT_TOTAL,2)
END)||'%' 成功金额占比
FROM (
SELECT
S0.FUND_CHANNEL_CODE
,S0.FUND_CHANNEL_NAME
,SUM(S0.ORDER_COUNT) ORDER_COUNT_TOTAL
,SUM(S0.ORDER_AMT) ORDER_AMT_TOTAL
FROM TMP_DM S0
GROUP BY S0.FUND_CHANNEL_CODE,S0.FUND_CHANNEL_NAME) S1
LEFT JOIN 
(SELECT
S0.FUND_CHANNEL_CODE
,S0.FUND_CHANNEL_NAME
,SUM(S0.ORDER_COUNT) ORDER_COUNT_SUCCESS
,SUM(S0.ORDER_AMT) ORDER_AMT_SUCCESS
FROM TMP_DM S0
WHERE S0.STATUS_NAME ='成功'
GROUP BY S0.FUND_CHANNEL_CODE,S0.FUND_CHANNEL_NAME
) S2
ON S1.FUND_CHANNEL_CODE=S2.FUND_CHANNEL_CODE
;